version: "3.7"
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    networks:
      - default
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: hakaton
      POSTGRES_USER: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    # expose:
    #   - "9000"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: moorik
      MINIO_ROOT_PASSWORD: 123456с
    command: server --console-address ":9001" /data
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ENDPOINT=http://minio:9000/
      - REGION=ru-1
      - AWS_ACCESS_KEY_ID=moorik
      - AWS_SECRET_ACCESS_KEY=123456с
      - BUCKET_NAME=1849ab3d-866b7a29-059e-4b31-b8ed-b9788e190712

    networks:
      - default
    depends_on:
      - database
    ports:
      - "8083:8080"
volumes:
  data:
  minio_storage:
