basePath: /
definitions:
  ent.Auth:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  ent.UserRequest:
    properties:
      login:
        type: string
      name:
        type: string
      password:
        type: string
      role_id:
        type: integer
    type: object
host: localhost:8083
info:
  contact: {}
  description: API Server for Site and Admin Application
  title: Hakaton
  version: "1.0"
paths:
  /api/auth/refresh/{refresh}:
    get:
      consumes:
      - application/json
      description: generate new pair of jwt and refresh
      operationId: gen new tokens
      parameters:
      - description: old refresh token
        in: path
        name: refresh
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: NewRefreshJwtTokens
      tags:
      - auth
  /api/auth/sign-in:
    post:
      consumes:
      - application/json
      description: auth in account
      operationId: auth in account
      parameters:
      - description: email and password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ent.Auth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
        default:
          description: ""
          schema:
            additionalProperties: true
            type: object
      summary: SignIn
      tags:
      - auth
  /api/auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ent.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
        default:
          description: ""
          schema:
            additionalProperties: true
            type: object
      summary: SignUp
      tags:
      - auth
  /api/class/dashboard:
    get:
      consumes:
      - application/json
      description: get child dashboard
      operationId: get-classes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
        default:
          description: ""
          schema:
            additionalProperties: true
            type: object
      security:
      - JwtKey: []
      summary: class
      tags:
      - class
  /api/class/my-classes:
    get:
      consumes:
      - application/json
      description: get child class
      operationId: get-classes child
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
        default:
          description: ""
          schema:
            additionalProperties: true
            type: object
      security:
      - JwtKey: []
      summary: class
      tags:
      - class
securityDefinitions:
  JwtKey:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
